config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :schedule_items
  resources :scores
  resources :subjects
  resources :objectives do
  	resources :assignments
  end
  resources :students do
  	resources :assignments
  end

  get '/students/:id/addObjective', to: 'students#addObjective', as: 'add_objective_to_student'
  post '/students/:id/addObjective', to: 'students#createAssignment'

  #TODO FIX this right
  get '/students/:id/deleteAssignment/:assignment_id', to: 'students#deleteAssignment', as: 'delete_objective_from_student'

  

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/dashboard/:day', to: 'dashboard#index', as: 'dashboard_day'
  post '/dashboard/:day', to: 'dashboard#getScores'
  post '/dashboard', to: 'dashboard#getScores'
  post '/', to: 'dashboard#getScores'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :assignments, dependent: :destroy
	has_many :scores, through: :assignments
	has_many :objectives, through: :assignments

	validates :name, presence: true
	validates :name, uniqueness: true
	
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :addObjective, :createAssignment, :deleteAssignment]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all.order(:name)
  end

  # GET /students/1/addObjective
  def addObjective

  end

  # POST /students/1/addObjective
  def createAssignment
    # @student.objectives << Objective.find(objective_params[:id])
    # Assignment.

    # respond_to do |format|
    #   format.html {redirect_to add_objective_to_student_path, notice: 'Assignment was successfully created.' }
    #   format.json { head :no_content }
    # end


    @assignment = Assignment.new(student_id:@student.id, objective_id:objective_params[:id])
    respond_to do |format|
      if @assignment.save
        format.html { redirect_to add_objective_to_student_path, notice: 'Assignment was successfully created.' }
        #format.json { render 'students#show', status: :created, location: @assignment.student}
      else
        format.html { redirect_to add_objective_to_student_path, notice: 'Student is already assigned that objective.' }
        #format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end


  end

  # GET /students/1/deleteObjective <-----SHOULD FIX TO POST
  def deleteAssignment
    @assignment = Assignment.find(params[:assignment_id])
    @assignment.destroy
    respond_to do |format|
      format.html {redirect_to add_objective_to_student_path, notice: 'Assignment was successfully destroyed.' }
      format.json { head :no_content }
    end

    
  end

  

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:name)
    end

    def objective_params
      params.require(:objective).permit(:id)
    end

end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/addObjective.html.haml
%p#notice= notice
%h1 Add/Delete Objectives for #{@student.name}
%ul
-@student.assignments.each do |a|
  %li
    = a.objective.description
    = link_to (fa_icon "trash"), delete_objective_from_student_path(:assignment_id => a.id)

= form_tag do
  = collection_select(:objective, :id, Objective.all, :id, :description, {:onchange => "this.form.submit()"})
  = submit_tag("Add",  {:class=>"btn btn-default"}) 

= link_to 'Back', @student

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.haml
%p#notice= notice
%h1 Students

- @students.each do |student|
  %h4= link_to student.name, student

%br/
= link_to 'Add New Student', new_student_path

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.haml
%p#notice= notice
%h2
  = @student.name
-if @student.objectives.size == 0
  %p
    %strong No Objectives
-else
  %strong Objectives

  %ul
    -@student.objectives.each do |obj|
      %li 
        =obj.description



= link_to 'Add Objective', add_objective_to_student_path
|
= link_to 'Edit Name', edit_student_path(@student)
|
= link_to 'Delete Student', @student, method: :delete, data: { confirm: 'Are you sure?' }
|
= link_to 'Back', students_path