config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :schedule_items
  resources :scores
  resources :subjects
  resources :objectives do
  	resources :assignments
  end
  resources :students do
  	resources :assignments
  end

  get '/students/:id/addObjective', to: 'students#addObjective', as: 'add_objective_to_student'
  post '/students/:id/addObjective', to: 'students#createAssignment'

  #TODO FIX this right
  get '/students/:id/deleteAssignment/:assignment_id', to: 'students#deleteAssignment', as: 'delete_objective_from_student'

  

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/dashboard/:day', to: 'dashboard#index', as: 'dashboard_day'
  post '/dashboard/:day', to: 'dashboard#getScores'
  post '/dashboard', to: 'dashboard#getScores'
  post '/', to: 'dashboard#getScores'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/objective.rb
class Objective < ApplicationRecord
	has_many :assignments
	has_many :students, through: :assignments
	has_many :scores, through: :assignments

	validates :description, presence: true
	validates :description, uniqueness: true
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
  before_action :set_objective, only: [:show, :edit, :update, :destroy]

  # GET /objectives
  # GET /objectives.json
  def index
    @objectives = Objective.all
  end

  # GET /objectives/1
  # GET /objectives/1.json
  def show
  end

  # GET /objectives/new
  def new
    @objective = Objective.new
  end

  # GET /objectives/1/edit
  def edit
  end

  # POST /objectives
  # POST /objectives.json
  def create
    @objective = Objective.new(objective_params)

    respond_to do |format|
      if @objective.save
        format.html { redirect_to @objective, notice: 'Objective was successfully created.' }
        format.json { render :show, status: :created, location: @objective }
      else
        format.html { render :new }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /objectives/1
  # PATCH/PUT /objectives/1.json
  def update
    respond_to do |format|
      if @objective.update(objective_params)
        format.html { redirect_to @objective, notice: 'Objective was successfully updated.' }
        format.json { render :show, status: :ok, location: @objective }
      else
        format.html { render :edit }
        format.json { render json: @objective.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /objectives/1
  # DELETE /objectives/1.json
  def destroy
    @objective.destroy
    respond_to do |format|
      format.html { redirect_to objectives_url, notice: 'Objective was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_objective
      @objective = Objective.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def objective_params
      params.require(:objective).permit(:description)
    end
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/views/objectives/_form.html.erb
<%= form_with(model: objective, local: true) do |form| %>
  <% if objective.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(objective.errors.count, "error") %> prohibited this objective from being saved:</h2>

      <ul>
      <% objective.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :objective_description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/objectives/edit.html.erb
= form_with(model: objective, local: true) do |form|
  - if objective.errors.any?
    #error_explanation
      %h2
        = pluralize(objective.errors.count, "error")
        prohibited this objective from being saved:
      %ul
        - objective.errors.full_messages.each do |message|
          %li= message
  .field
    = form.label :description
    = form.text_field :description, id: :objective_description
  .actions
    = form.submit

app/views/objectives/index.html.haml
%p#notice= notice
%h1 Objectives
- @objectives.each do |objective|
  %h4
    = link_to objective.description, objective

  = link_to 'Edit', edit_objective_path(objective)
  |
  = link_to 'Delete', objective, method: :delete, data: { confirm: 'Are you sure?' }
%br/
%h3
  = link_to 'New Objective', new_objective_path

app/views/objectives/new.html.erb
<h1>New Objective</h1>

<%= render 'form', objective: @objective %>

<%= link_to 'Back', objectives_path %>

app/views/objectives/show.html.haml
%p#notice= notice

%p
  %strong Description:
  = @objective.description 

%strong Students with this objective
%ul
  -@objective.students.each do |s|
    %li=s.name

= link_to 'Edit', edit_objective_path(@objective)
|
= link_to 'Back', objectives_path 