config/routes.rb
Rails.application.routes.draw do
  root "dashboard#index"
  resources :schedule_items
  resources :scores
  resources :subjects
  resources :objectives do
  	resources :assignments
  end
  resources :students do
  	resources :assignments
  end

  get '/students/:id/addObjective', to: 'students#addObjective', as: 'add_objective_to_student'
  post '/students/:id/addObjective', to: 'students#createAssignment'

  #TODO FIX this right
  get '/students/:id/deleteAssignment/:assignment_id', to: 'students#deleteAssignment', as: 'delete_objective_from_student'

  

  get '/dashboard', to: 'dashboard#index', as: 'dashboard'
  get '/dashboard/:day', to: 'dashboard#index', as: 'dashboard_day'
  post '/dashboard/:day', to: 'dashboard#getScores'
  post '/dashboard', to: 'dashboard#getScores'
  post '/', to: 'dashboard#getScores'


  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
	has_many :schedule_items
	has_many :scores, through: :schedule_items

	validates :name, presence: true
	validates :name, uniqueness: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :set_subject, only: [:show, :edit, :update, :destroy]

  # GET /subjects
  # GET /subjects.json
  def index
    @subjects = Subject.all
  end

  # GET /subjects/1
  # GET /subjects/1.json
  def show
  end

  # GET /subjects/new
  def new
    @subject = Subject.new
  end

  # GET /subjects/1/edit
  def edit
  end

  # POST /subjects
  # POST /subjects.json
  def create
    @subject = Subject.new(subject_params)

    respond_to do |format|
      if @subject.save
        format.html { redirect_to @subject, notice: 'Subject was successfully created.' }
        format.json { render :show, status: :created, location: @subject }
      else
        format.html { render :new }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subjects/1
  # PATCH/PUT /subjects/1.json
  def update
    respond_to do |format|
      if @subject.update(subject_params)
        format.html { redirect_to @subject, notice: 'Subject was successfully updated.' }
        format.json { render :show, status: :ok, location: @subject }
      else
        format.html { render :edit }
        format.json { render json: @subject.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subjects/1
  # DELETE /subjects/1.json
  def destroy
    @subject.destroy
    respond_to do |format|
      format.html { redirect_to subjects_url, notice: 'Subject was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subject
      @subject = Subject.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subject_params
      params.require(:subject).permit(:time, :name)
    end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_form.html.erb
<%= form_with(model: subject, local: true) do |form| %>
  <% if subject.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(subject.errors.count, "error") %> prohibited this subject from being saved:</h2>

      <ul>
      <% subject.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :subject_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/subjects/edit.html.erb
<h1>Editing Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Show', @subject %> |
<%= link_to 'Back', subjects_path %>

app/views/subjects/index.html.haml
%p#notice= notice
%h1 Subjects
- @subjects.each do |subject|
  %h4
    = subject.name
  = link_to 'Edit', edit_subject_path(subject)
  |
  = link_to 'Delete', subject, method: :delete, data: { confirm: 'Are you sure?' }
%br/
%h3
  = link_to 'New Subject', new_subject_path

app/views/subjects/new.html.erb
<h1>New Subject</h1>

<%= render 'form', subject: @subject %>

<%= link_to 'Back', subjects_path %>

app/views/subjects/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Name:</strong>
  <%= @subject.name %>
</p>

<%= link_to 'Edit', edit_subject_path(@subject) %> |
<%= link_to 'Back', subjects_path %>